export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";